use crate::types::Tree;

pub const TREES: &[Tree] = &[
    Tree {
        name_english: "Cedar",
        name_latin: "Cedrus",
        typical_height_m: None,
        identifiable_features: "Scale leaves in spiral clusters",
    },
    Tree {
        name_english: "Juniper",
        name_latin: "Juniperus",
        typical_height_m: Some(30),
        identifiable_features: "Scale leaves; dark blue berry-like cones",
    },
    Tree {
        name_english: "Oak",
        name_latin: "Quercus",
        typical_height_m: None,
        identifiable_features: "Lobed leaves; Acorns",
    },
    Tree {
        name_english: "Sycamore",
        name_latin: "Platanus",
        typical_height_m: None,
        identifiable_features: "Thin, peeling reddish-brown bark",
    },
    Tree {
        name_english: "Willow",
        name_latin: "Salix",
        typical_height_m: None,
        identifiable_features: "Long drooping branches",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
    Tree {
        name_english: "Space filler",
        name_latin: "Space filler",
        typical_height_m: None,
        identifiable_features: "Space filler",
    },
];
